name: rpcs3-emulator
base: core24
adopt-info: rpcs3-app
platforms:
  amd64:
    build-on: [amd64]
    build-for: [amd64]
  arm64:
    build-on: [arm64]
    build-for: [arm64]
summary: Open-source Sony PlayStation 3 Emulator
description: |
  RPCS3 is an experimental open-source Sony PlayStation 3 emulator and debugger written in C++ for Windows and Linux.
  RPCS3 started development in May of 2011 by its founders DH and Hykem.
  The emulator is currently capable of running over 2500 commercial titles powered by Vulkan and OpenGL.
  The goal of this project is to experiment, research, and educate on the topic of PlayStation 3 emulation that can be performed on compatible devices and operating systems.
  All information was obtained legally by purchasing PlayStation 3 hardware and software. Additional information was obtained from various sources on the internet that include but is not limited to system hardware and software documentation.
  Most of this information can be found on the PlayStation 3 Developer Wiki.
grade: stable
confinement: strict
icon: rpcs3.svg

apps:
  rpcs3-emulator:
    command-chain: [snap/command-chain/override-xdg-paths]
    command: usr/bin/rpcs3
    desktop: usr/share/applications/rpcs3.desktop
    common-id: net.rpcs3.RPCS3
    environment:
      QT_QPA_PLATFORMTHEME: xdgdesktopportal
    extensions: [gnome]
    plugs:
      - unity7
      - screen-inhibit-control
      - audio-playback
      - network
      - network-bind
      - home
      - removable-media
      - mount-observe
      - joystick
      - bluez
      - udisks2
      - raw-usb

plugs:
  shared-memory:
    private: true

parts:
  rpcs3-app:
    plugin: nil
    build-packages: [wget, curl]
    override-build: |
      if [ "$CRAFT_ARCH_TRIPLET_BUILD_FOR" = "x86_64-linux-gnu" ]; then
        URL=$(curl -s "https://api.github.com/repos/RPCS3/rpcs3-binaries-linux/releases/latest" | grep -o 'https.*linux64\.AppImage' | head -1)
        wget "$URL"
      elif [ "$CRAFT_ARCH_TRIPLET_BUILD_FOR" = "aarch64-linux-gnu" ]; then
        URL=$(curl -s "https://api.github.com/repos/RPCS3/rpcs3-binaries-linux-arm64/releases/latest" | grep -o 'https.*linux_aarch64\.AppImage' | head -1)
        wget "$URL"
      fi
      
      APPIMAGE_FILE=$(basename "$URL")
      chmod +x "$APPIMAGE_FILE"
      ./"$APPIMAGE_FILE" --appimage-extract
      mv -f AppDir/usr $CRAFT_PART_INSTALL/usr

      sed -i 's|Name=RPCS3|Name=RPCS3 [Kyu]|' $CRAFT_PART_INSTALL/usr/share/applications/rpcs3.desktop

      VERSION=$(echo "$APPIMAGE_FILE" | sed -n 's/.*rpcs3-v\([0-9.]*\)-\([0-9]*\)-.*/\1-\2/p')
      craftctl set version="$VERSION"
    prime:
      - usr

  command-chain:
    after: [rpcs3-app]
    plugin: dump
    source: ./command-chain/
    organize:
      override-xdg-paths: snap/command-chain/override-xdg-paths
