name: rpcs3-emulator
base: core24
version: '0.0.37-18090'
platforms:
  amd64:
    build-on: [amd64]
    build-for: [amd64]
summary: Open-source Sony PlayStation 3 Emulator
description: |
  RPCS3 is an experimental open-source Sony PlayStation 3 emulator and debugger written in C++ for Windows and Linux. RPCS3 started development in May of 2011 by its founders DH and Hykem. The emulator is currently capable of running over 2500 commercial titles powered by Vulkan and OpenGL.

  The goal of this project is to experiment, research, and educate on the topic of PlayStation 3 emulation that can be performed on compatible devices and operating systems. All information was obtained legally by purchasing PlayStation 3 hardware and software. Additional information was obtained from various sources on the internet that include but is not limited to system hardware and software documentation. Most of this information can be found on the PlayStation 3 Developer Wiki.

grade: stable
confinement: strict

apps:
  rpcs3-emulator:
    command: usr/bin/rpcs3
    desktop: usr/share/applications/rpcs3.desktop
    extensions:
      - gnome
    plugs:
      - home
      - removable-media
      - gtk-3-themes
      - icon-themes
      - desktop
      - desktop-legacy
      - x11
      - opengl
      - wayland
      - audio-playback
      - joystick
      - screen-inhibit-control
      - network

parts:
  rpcs3-emulator:
    plugin: dump
    source: .
    build-packages:
      - wget
    override-build: |
      craftctl default
      pwd
      ls -l
      wget https://github.com/RPCS3/rpcs3-binaries-linux/releases/download/build-e319ca299820cb4009386059f2ba830a9b698274/rpcs3-v0.0.37-18090-e319ca29_linux64.AppImage
      chmod +x rpcs3-v0.0.37-18090-e319ca29_linux64.AppImage
      ./rpcs3-v0.0.37-18090-e319ca29_linux64.AppImage --appimage-extract
      mkdir -p $CRAFT_PART_INSTALL/
      sed -i 's|Icon=rpcs3|Icon=${SNAP}/usr/share/icons/hicolor/scalable/apps/rpcs3.svg|' AppDir/usr/share/applications/rpcs3.desktop
      sed -i 's|Exec=rpcs3 %f|Exec=${SNAP}/usr/bin/rpcs3 %f|' AppDir/usr/share/applications/rpcs3.desktop
      sed -i 's|TryExec=rpcs3|TryExec=${SNAP}/usr/bin/rpcs3|' AppDir/usr/share/applications/rpcs3.desktop
      mv -f AppDir/usr $CRAFT_PART_INSTALL/
    prime:
      - usr
